<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction

Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones.

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.

Therefore if we can determine if the first stage will land, we can determine the cost of a launch.

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

<a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">Spacex DataSet</a>

### Store the dataset in database table

**it is highly recommended to manually load the table using the database console LOAD tool in DB2**.

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload.png">

Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the  dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new table as follows:

**SPACEXDATASET**

**Follow these steps while using old DB2 UI which is having Open Console Screen**

**Note:While loading Spacex dataset, ensure that detect datatypes is disabled. Later click on the pencil icon(edit option).**

1.  Change the Date Format by manually typing DD-MM-YYYY and timestamp format as DD-MM-YYYY HH\:MM:SS

2.  Change the PAYLOAD_MASS\_\_KG\_  datatype  to INTEGER.

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload2.png">

**Changes to be considered when having DB2 instance with the new UI having Go to UI screen**

*   Refer to this insruction in this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">link</a> for viewing  the new  Go to UI screen.

*   Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.

*   Later browse for the downloaded spacex file.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png" width="800"/>

*   Once done select the schema andload the file.

 <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png" width="800"/>

In [1]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 82.3 MB/s eta 0:00:00:00:0100:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp37-cp37m-linux_x86_64.whl size=1159121 sha256=87c41d474b1d81b7b4e6680cbb4c3a70eb0a3b7300afbd13570ac4410038ed73
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/03/71/13/010faf12246f72dc76b4150e6e599d13a85b4435e06fb9e51f
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.24
    Uninstalling SQLAlchemy-1.3.24:
      Successfully uninstalled SQLAlchemy-1.3.24
Successfully installed sqlalchemy-1.3.9

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
%load_ext sql

In [3]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [4]:
!pip install -q pandas==1.1.5

In [5]:
%sql sqlite:///my_data1.db

'Connected: @my_data1.db'

In [16]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/pandas/core/generic.py:2882: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  both result in 0.1234 being formatted as 0.12.

In [18]:
df_csv = pd.read_csv('Spacex.csv')
df_csv.head()

ModuleNotFoundError: No module named 'pandas.io.formats.string'

ImportError: cannot import name 'TableFormatter' from 'pandas.io.formats.format' (/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/pandas/io/formats/format.py)

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
For Example "Landing_Outcome"**

### Task 1

##### Display the names of the unique launch sites  in the space mission

In [12]:
cur.execute("SELECT DISTINCT Launch_Site FROM SPACEXTBL")
cur.fetchall()

[('CCAFS LC-40',), ('VAFB SLC-4E',), ('KSC LC-39A',), ('CCAFS SLC-40',)]

### Task 2

##### Display 5 records where launch sites begin with the string 'CCA'

In [14]:
cur.execute("SELECT * FROM SPACEXTBL WHERE Launch_Site LIKE 'CCA%'")
cur.fetchall()

[('04-06-2010',
  '18:45:00',
  'F9 v1.0  B0003',
  'CCAFS LC-40',
  'Dragon Spacecraft Qualification Unit',
  0,
  'LEO',
  'SpaceX',
  'Success',
  'Failure (parachute)'),
 ('08-12-2010',
  '15:43:00',
  'F9 v1.0  B0004',
  'CCAFS LC-40',
  'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese',
  0,
  'LEO (ISS)',
  'NASA (COTS) NRO',
  'Success',
  'Failure (parachute)'),
 ('22-05-2012',
  '07:44:00',
  'F9 v1.0  B0005',
  'CCAFS LC-40',
  'Dragon demo flight C2',
  525,
  'LEO (ISS)',
  'NASA (COTS)',
  'Success',
  'No attempt'),
 ('08-10-2012',
  '00:35:00',
  'F9 v1.0  B0006',
  'CCAFS LC-40',
  'SpaceX CRS-1',
  500,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('01-03-2013',
  '15:10:00',
  'F9 v1.0  B0007',
  'CCAFS LC-40',
  'SpaceX CRS-2',
  677,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('03-12-2013',
  '22:41:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'SES-8',
  3170,
  'GTO',
  'SES',
  'Success',
  'No attempt'),
 ('06-01-2014',
  '22:06:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'Thaicom 6',
  3325,
  'GTO',
  'Thaicom',
  'Success',
  'No attempt'),
 ('18-04-2014',
  '19:25:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'SpaceX CRS-3',
  2296,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Controlled (ocean)'),
 ('14-07-2014',
  '15:15:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'OG2 Mission 1  6 Orbcomm-OG2 satellites',
  1316,
  'LEO',
  'Orbcomm',
  'Success',
  'Controlled (ocean)'),
 ('05-08-2014',
  '08:00:00',
  'F9 v1.1',
  'CCAFS LC-40',
  'AsiaSat 8',
  4535,
  'GTO',
  'AsiaSat',
  'Success',
  'No attempt'),
 ('07-09-2014',
  '05:00:00',
  'F9 v1.1 B1011',
  'CCAFS LC-40',
  'AsiaSat 6',
  4428,
  'GTO',
  'AsiaSat',
  'Success',
  'No attempt'),
 ('21-09-2014',
  '05:52:00',
  'F9 v1.1 B1010',
  'CCAFS LC-40',
  'SpaceX CRS-4',
  2216,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Uncontrolled (ocean)'),
 ('10-01-2015',
  '09:47:00',
  'F9 v1.1 B1012',
  'CCAFS LC-40',
  'SpaceX CRS-5',
  2395,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure (drone ship)'),
 ('11-02-2015',
  '23:03:00',
  'F9 v1.1 B1013',
  'CCAFS LC-40',
  'DSCOVR',
  570,
  'HEO',
  'U.S. Air Force NASA NOAA',
  'Success',
  'Controlled (ocean)'),
 ('02-03-2015',
  '03:50:00',
  'F9 v1.1 B1014',
  'CCAFS LC-40',
  'ABS-3A Eutelsat 115 West B',
  4159,
  'GTO',
  'ABS Eutelsat',
  'Success',
  'No attempt'),
 ('14-04-2015',
  '20:10:00',
  'F9 v1.1 B1015',
  'CCAFS LC-40',
  'SpaceX CRS-6',
  1898,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure (drone ship)'),
 ('27-04-2015',
  '23:03:00',
  'F9 v1.1 B1016',
  'CCAFS LC-40',
  'Turkmen 52 / MonacoSAT',
  4707,
  'GTO',
  'Turkmenistan National Space Agency',
  'Success',
  'No attempt'),
 ('28-06-2015',
  '14:21:00',
  'F9 v1.1 B1018',
  'CCAFS LC-40',
  'SpaceX CRS-7',
  1952,
  'LEO (ISS)',
  'NASA (CRS)',
  'Failure (in flight)',
  'Precluded (drone ship)'),
 ('22-12-2015',
  '01:29:00',
  'F9 FT B1019',
  'CCAFS LC-40',
  'OG2 Mission 2  11 Orbcomm-OG2 satellites',
  2034,
  'LEO',
  'Orbcomm',
  'Success',
  'Success (ground pad)'),
 ('04-03-2016',
  '23:35:00',
  'F9 FT B1020',
  'CCAFS LC-40',
  'SES-9',
  5271,
  'GTO',
  'SES',
  'Success',
  'Failure (drone ship)'),
 ('08-04-2016',
  '20:43:00',
  'F9 FT B1021.1',
  'CCAFS LC-40',
  'SpaceX CRS-8',
  3136,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (drone ship)'),
 ('06-05-2016',
  '05:21:00',
  'F9 FT B1022',
  'CCAFS LC-40',
  'JCSAT-14',
  4696,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'),
 ('27-05-2016',
  '21:39:00',
  'F9 FT B1023.1',
  'CCAFS LC-40',
  'Thaicom 8',
  3100,
  'GTO',
  'Thaicom',
  'Success',
  'Success (drone ship)'),
 ('15-06-2016',
  '14:29:00',
  'F9 FT B1024',
  'CCAFS LC-40',
  'ABS-2A Eutelsat 117 West B',
  3600,
  'GTO',
  'ABS Eutelsat',
  'Success',
  'Failure (drone ship)'),
 ('18-07-2016',
  '04:45:00',
  'F9 FT B1025.1',
  'CCAFS LC-40',
  'SpaceX CRS-9',
  2257,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'),
 ('14-08-2016',
  '05:26:00',
  'F9 FT B1026',
  'CCAFS LC-40',
  'JCSAT-16',
  4600,
  'GTO',
  'SKY Perfect JSAT Group',
  'Success',
  'Success (drone ship)'),
 ('15-12-2017',
  '15:36:00',
  'F9 FT  B1035.2',
  'CCAFS SLC-40',
  'SpaceX CRS-13',
  2205,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success (ground pad)'),
 ('08-01-2018',
  '01:00:00',
  'F9 B4 B1043.1',
  'CCAFS SLC-40',
  'Zuma',
  5000,
  'LEO',
  'Northrop Grumman',
  'Success (payload status unclear)',
  'Success (ground pad)'),
 ('31-01-2018',
  '21:25:00',
  'F9 FT  B1032.2',
  'CCAFS SLC-40',
  'GovSat-1 / SES-16',
  4230,
  'GTO',
  'SES',
  'Success',
  'Controlled (ocean)'),
 ('06-03-2018',
  '05:33:00',
  'F9 B4 B1044',
  'CCAFS SLC-40',
  'Hispasat 30W-6  PODSat',
  6092,
  'GTO',
  'Hispasat  NovaWurks',
  'Success',
  'No attempt'),
 ('02-04-2018',
  '20:30:00',
  'F9 B4  B1039.2',
  'CCAFS SLC-40',
  'SpaceX CRS-14',
  2647,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('18-04-2018',
  '22:51:00',
  'F9 B4 B1045.1',
  'CCAFS SLC-40',
  'Transiting Exoplanet Survey Satellite (TESS)',
  362,
  'HEO',
  'NASA (LSP)',
  'Success',
  'Success (drone ship)'),
 ('04-06-2018',
  '04:45:00',
  'F9 B4  B1040.2',
  'CCAFS SLC-40',
  'SES-12',
  5384,
  'GTO',
  'SES',
  'Success',
  'No attempt'),
 ('29-06-2018',
  '09:42:00',
  'F9 B4 B1045.2',
  'CCAFS SLC-40',
  'SpaceX CRS-15',
  2697,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'No attempt'),
 ('22-07-2018',
  '05:50:00',
  'F9 B5B1047.1',
  'CCAFS SLC-40',
  'Telstar 19V',
  7075,
  'GTO',
  'Telesat',
  'Success',
  'Success'),
 ('07-08-2018',
  '05:18:00',
  'F9 B5 B1046.2',
  'CCAFS SLC-40',
  'Merah Putih ',
  5800,
  'GTO',
  'Telkom Indonesia',
  'Success',
  'Success'),
 ('10-09-2018',
  '04:45:00',
  'F9 B5B1049.1',
  'CCAFS SLC-40',
  'Telstar 18V / Apstar-5C',
  7060,
  'GTO',
  'Telesat',
  'Success',
  'Success'),
 ('05-12-2018',
  '18:16:00',
  'F9 B5B1050',
  'CCAFS SLC-40',
  'SpaceX CRS-16',
  2500,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Failure'),
 ('23-12-2018',
  '13:51:00',
  'F9 B5B1054',
  'CCAFS SLC-40',
  'GPS III-01 ',
  4400,
  'MEO',
  'USAF',
  'Success ',
  'No attempt'),
 ('22-02-2019',
  '01:45:00',
  'F9 B5 B1048.3',
  'CCAFS SLC-40',
  'Nusantara Satu, Beresheet Moon lander, S5',
  4850,
  'GTO',
  'PSN, SpaceIL / IAI',
  'Success',
  'Success'),
 ('04-05-2019',
  '06:48:00',
  'F9 B5B1056.1 ',
  'CCAFS SLC-40',
  'SpaceX CRS-17, Starlink v0.9',
  2495,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'),
 ('24-05-2019',
  '02:30:00',
  'F9 B5 B1049.3',
  'CCAFS SLC-40',
  'Starlink v0.9, RADARSAT Constellation',
  13620,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('25-07-2019',
  '22:01:00',
  'F9 B5 B1056.2 ',
  'CCAFS SLC-40',
  'SpaceX CRS-18, AMOS-17 ',
  2268,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'),
 ('06-08-2019',
  '23:23:00',
  'F9 B5 B1047.3 ',
  'CCAFS SLC-40',
  'AMOS-17, Starlink 1 v1.0 ',
  6500,
  'GTO',
  'Spacecom',
  'Success',
  'No attempt '),
 ('11-11-2019',
  '14:56:00',
  'F9 B5 B1048.4',
  'CCAFS SLC-40',
  'Starlink 1 v1.0, SpaceX CRS-19 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('05-12-2019',
  '17:29:00',
  'F9 B5B1059.1',
  'CCAFS SLC-40',
  'SpaceX CRS-19, JCSat-18 / Kacific 1 ',
  2617,
  'LEO (ISS)',
  'NASA (CRS), Kacific 1',
  'Success',
  'Success'),
 ('17-12-2019',
  '00:10:00',
  'F9 B5 B1056.3 ',
  'CCAFS SLC-40',
  'JCSat-18 / Kacific 1, Starlink 2 v1.0 ',
  6956,
  'GTO',
  'Sky Perfect JSAT, Kacific 1',
  'Success',
  'Success'),
 ('07-01-2020',
  '02:33:00',
  'F9 B5 B1049.4',
  'CCAFS SLC-40',
  'Starlink 2 v1.0, Crew Dragon in-flight abort test ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('29-01-2020',
  '14:07:00',
  'F9 B5 B1051.3',
  'CCAFS SLC-40',
  'Starlink 3 v1.0, Starlink 4 v1.0 ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('17-02-2020',
  '15:05:00',
  'F9 B5 B1056.4',
  'CCAFS SLC-40',
  'Starlink 4 v1.0, SpaceX CRS-20',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Failure'),
 ('07-03-2020',
  '04:50:00',
  'F9 B5 B1059.2',
  'CCAFS SLC-40',
  'SpaceX CRS-20, Starlink 5 v1.0 ',
  1977,
  'LEO (ISS)',
  'NASA (CRS)',
  'Success',
  'Success'),
 ('04-06-2020',
  '01:25:00',
  'F9 B5 B1049.5',
  'CCAFS SLC-40',
  'Starlink 7 v1.0, Starlink 8 v1.0',
  15600,
  'LEO',
  'SpaceX, Planet Labs',
  'Success',
  'Success'),
 ('13-06-2020',
  '09:21:00',
  'F9 B5 B1059.3',
  'CCAFS SLC-40',
  'Starlink 8 v1.0, SkySats-16, -17, -18, GPS III-03 ',
  15410,
  'LEO',
  'SpaceX, Planet Labs',
  'Success',
  'Success'),
 ('30-06-2020',
  '20:10:46',
  'F9 B5B1060.1',
  'CCAFS SLC-40',
  'GPS III-03, ANASIS-II',
  4311,
  'MEO',
  'U.S. Space Force',
  'Success',
  'Success'),
 ('20-07-2020',
  '21:30:00',
  'F9 B5 B1058.2 ',
  'CCAFS SLC-40',
  'ANASIS-II, Starlink 9 v1.0',
  5500,
  'GTO',
  'Republic of Korea Army, Spaceflight Industries (BlackSky)',
  'Success',
  'Success'),
 ('18-08-2020',
  '14:31:00',
  'F9 B5 B1049.6',
  'CCAFS SLC-40',
  'Starlink 10 v1.0, SkySat-19, -20, -21, SAOCOM 1B ',
  15440,
  'LEO',
  'SpaceX, Planet Labs, PlanetIQ',
  'Success',
  'Success'),
 ('30-08-2020',
  '23:18:00',
  'F9 B5 B1059.4',
  'CCAFS SLC-40',
  'SAOCOM 1B, GNOMES 1, Tyvak-0172',
  3130,
  'SSO',
  'CONAE, PlanetIQ, SpaceX',
  'Success',
  'Success'),
 ('24-10-2020',
  '15:31:34',
  'F9 B5 B1060.3',
  'CCAFS SLC-40',
  'Starlink 14 v1.0, GPS III-04  ',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success'),
 ('05-11-2020',
  '23:24:23',
  'F9 B5B1062.1',
  'CCAFS SLC-40',
  'GPS III-04 , Crew-1',
  4311,
  'MEO',
  'USSF',
  'Success',
  'Success'),
 ('25-11-2020',
  '02:13:00',
  'F9 B5 B1049.7 ',
  'CCAFS SLC-40',
  'Starlink 15 v1.0, SpaceX CRS-21',
  15600,
  'LEO',
  'SpaceX',
  'Success',
  'Success')]

### Task 3

##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [20]:
cur.execute('SELECT SUM(PAYLOAD_MASS__KG_) FROM SPACEXTBL WHERE Customer="NASA (CRS)"')
cur.fetchall()

[(45596,)]

### Task 4

##### Display average payload mass carried by booster version F9 v1.1

In [21]:
cur.execute('SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEXTBL WHERE Booster_Version="F9 v1.1"')
cur.fetchall()

[(2928.4,)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.

*Hint:Use min function*

In [ ]:
cur.execute('SELECT min(Date)')

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

### Task 7

##### List the total number of successful and failure mission outcomes

### Task 8

##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

### Task 9

##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 4, 2) as month to get the months and substr(Date,7,4)='2015' for year.**

### Task 10

##### Rank the  count of  successful landing_outcomes between the date 04-06-2010 and 20-03-2017 in descending order.

### Reference Links

*   <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01&origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01&origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01&origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*   <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log

| Date       | Version | Changed by    | Change Description        |
| ---------- | ------- | ------------- | ------------------------- |
| 2021-07-09 | 0.2     | Lakshmi Holla | Changes made in magic sql |
| 2021-05-20 | 0.1     | Lakshmi Holla | Created Initial Version   |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>